name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install tox tox-uv
      - name: Test with tox
        run: tox
      - name: Test with doctest
        run: |
          python -m pip install -e .
          python -m doctest src/python/bag3d/specs/core.py -v
